# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: carlyle
      MYSQL_DATABASE: carlyle

  redis:
    image: redis:3.2.11-alpine
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
